name: Simple Continuous Integration

on: [push]

jobs: 
  test:
    runs-on: ubuntu-latest
  
    steps:
      - name: echo a string
        run: echo "Hello GitHub Action!!"
      - name: Java Check
        run: java --version
      - uses: actions/checkout@v3
      - name: Set up Java 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Java Check
        run: java --version
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew test
    